from typing import Protocol, Any


class HorizonAdapter(Protocol):
    epoch: str

    def boot(self, profile: dict | None, trusted_context: dict, budget: int) -> dict: ...
    def realize_application(self, package_ref: dict, authority: dict, budget: int) -> dict: ...
    def observe(self, view_context: dict, projection_cursor: Any = None) -> dict: ...
    def execute(self, intent: dict, authority: dict, budget: int) -> dict: ...
    def lookup_outcome(self, operation_key: tuple[str, str, str]) -> dict | None: ...
    def checkpoint(self, authority: dict) -> dict: ...
    def restore(self, checkpoint_ref: dict, authority: dict, budget: int) -> dict: ...
    def quiesce(self, budget: int) -> dict: ...
    def close(self) -> dict: ...
