CODES = frozenset('MALFORMED_FRAME UNSUPPORTED_VERSION UNBOUND_SESSION AUTHORITY_DENIED UNKNOWN_APPLICATION UNKNOWN_OPERATION STALE_PRECONDITION INVALID_ROUTE ADMISSION_REJECTED CLOSURE_FAILED BUDGET_EXCEEDED REQUEST_ID_CONFLICT RETRY_EXPIRED BACKPRESSURE COMMITTED_DELIVERY_PENDING RUNTIME_FAULT'.split())


class BoundaryError(ValueError):
    def __init__(self, code='MALFORMED_FRAME'):
        self.code = code if code in CODES else 'RUNTIME_FAULT'
        super().__init__(self.code)
